### ISSUE TITLE
Feature Requests 功能请求

### ISSUE THREAD

**Issue by linser233** [FT-Fetters/DockerPull#17]
下载镜像的时候是有架构选项的 但是文件名中没有 如果下载同一个版本的会替换掉另外的 架构不一样的情况下，这对使用造成很大的困扰，能不能在.tar.gz之前 加上_$ARCH以作为区分？
There is an architecture option when downloading the image but not in the filename If you download the same version it replaces the other one with a different architecture, this causes a lot of problems with usage, can you add _$ARCH before the .tar.gz to differentiate?

**Comment by linser233** [comment]
aaa/bbb:ccc@_$ARCH
like this
aaa_bbb_ccc.tar.gz > aaa_bbb_ccc_amd64.tar.gz

**Comment by FT-Fetters** [comment]
Due to the old code design problem, the old command and the web download can only be distinguished by digest. It is recommended to use the new pull command, modified in web1.3.1.
