### ISSUE TITLE
没有办法下载其他仓库的镜像吗？比如ghcr.io开头的

### ISSUE THREAD

**Issue by sqt2lxf** [FT-Fetters/DockerPull#7]
![image](https://github.com/user-attachments/assets/38e6c28e-b027-4de7-a511-dcc0474380aa)
![image](https://github.com/user-attachments/assets/1eb8c318-047d-40aa-a53f-fb07c5878a23)

**Comment by FT-Fetters** [comment]
后续有空会考虑增加哦

**Comment by FT-Fetters** [comment]
已在web1.3添加
